[package]
name = "github-summary"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
octocrab = "0.49.5"
ollama-rs = { version = "0.3.3", default-features = false, features = ["rustls"] }
serde = "1.0.228"
serde_json = "1.0.148"
tokio = { version = "1.49.0", features = ["full"] }
